class Listing < ActiveRecord::Base
  # set primary key to listing ID
  # NOT necessary for eager loading of prop_media
  # self.primary_key = "ListingID"

  belongs_to :agent
  belongs_to :broker

  has_many :property_media, :primary_key => :ListingID, :foreign_key => :ListingID

  def self.find_by_sql_with_associations(query)
    listings = find_by_sql(query)
    ActiveRecord::Associations::Preloader.new(listings, [:property_media, {:PropMimeType => 'IMAGE_JPEG'}]).run
    return listings
  end

  def self.less_than(property, value)
    where("\"#{property}\" < ?", "#{value}")
  end

  def self.greater_than(property, value)
    where("\"#{property}\" > ?", "#{value}")
  end

  # list of all cities
  # this list is 10.9KB, probably should use autocomplete
  ALL_CITIES = ["29 Palms", "Acton", "Adelanto", "Agoura Hills", 
    "Agua Dulce", "Aguanga", "Ahwahnee", "Alameda", 
    "Alamo", "Alhambra", "Aliso Viejo", "Almanor", 
    "Alpine", "Alta Loma", "Altadena", "Amador City", 
    "Anaheim", "Anaheim Hills", "Anderson", "Angels Camp", 
    "Angelus Oaks", "Antelope", "Antioch", "Anza", 
    "Apple Valley", "Arboga", "Arcadia", "Arleta", 
    "Arlington", "Arrowbear", "Arroyo Grande", "Artesia", 
    "Artois", "Arvin", "Atascadero", "Athens", 
    "Atwater", "Atwater Village", "Avalon", "Azusa", 
    "Baker", "Bakersfield", "Baldwin Hills", "Baldwin Park", 
    "Bangor", "Banning", "Barstow", "Bass Lake", 
    "Bay Point", "Bear Valley Springs", "Beaumont", "Bel Air", 
    "Bell", "Bell Canyon", "Bell Gardens", "Bellflower", 
    "Bermuda Dunes", "Berry Creek", "Bethel Island", "Beverly Hills", 
    "Big Bear", "Big Pine", "Big River", "Bigfork", 
    "Biggs", "Birds Landing", "Birmingham", "Blairsden", 
    "Bloomington", "Blue Jay", "Blue Springs", "Blythe", 
    "Bodfish", "Bonanza", "Bonita", "Bonsall", 
    "Boron", "Borrego Springs", "Boston", "Bradbury", 
    "Brawley", "Brea", "Browns Valley", "Brownsville", 
    "Brush Creek", "Buellton", "Buena Park", "Bullhead City", 
    "Burbank", "Butte City", "Butte Meadows", "Butte Valley", 
    "Cabazon", "Calabasas", "Calabasas Highlands", "Calabasas Park", 
    "Calexico", "Caliente", "California City", "Calimesa", 
    "Calipatria", "Calistoga", "Calpine", "Camarillo", 
    "Campo", "Camptonville", "Canoga Park", "Canyon Country", 
    "Canyon Lake", "Cardiff by the Sea", "Carefree", "Carlsbad", 
    "Carmichael", "Carpinteria", "Carson", "Caruthers", 
    "Castaic", "Castro Valley", "Cathedral City", "Catheys Valley", 
    "Cayucos", "Cedar Glen", "Cedarpines Park", "Ceres", 
    "Cerritos", "Charlotte", "Chatham Center", "Chatsworth", 
    "Cherry Valley", "Chester", "Chico", "Chilcoot", 
    "Chino", "Chino Hills", "Chowchilla", "Chula Vista", 
    "City of Commerce", "Claremont", "Clear Creek", "Clearlake", 
    "Clearlake Oaks", "Clearlake Park", "Clements", "Clio", 
    "Clipper Mills", "Clovis", "Coachella", "Coalinga", 
    "Coarsegold", "Cobb", "Cohasset", "Colton", 
    "Columbus", "Colusa", "Compton", "Concord", 
    "Corning", "Corona", "Corona del Mar", "Coronado", 
    "Costa Mesa", "Coto de Caza", "Cottonwood", "Coulterville", 
    "Covelo", "Covina", "Crescent Mills", "Cressey", 
    "Crestline", "Cromberg", "Cudahy", "Culver City", 
    "Cypress", "Dairyville", "Daly City", "Dana Point", 
    "Del Mar", "Delano", "Delhi", "Delleker", 
    "Denair", "Desert Center", "Desert Hot Springs", "Desert Shores", 
    "Diamond Bar", "Diamond Springs", "Dinuba", "Discovery Bay", 
    "Dixon", "Dobbins", "Dos Palos", "Downey", 
    "Drytown", "Duarte", "Dunsmuir", "Durham", 
    "Eagle Rock", "East Los Angeles", "El Cajon", "El Centro", 
    "El Dorado", "El Mirage", "El Monte", "El Segundo", 
    "El Sereno", "El Toro", "Elk Creek", "Elk Grove", 
    "Encinitas", "Encino", "Escanaba", "Escondido", 
    "Exeter", "Fair Oaks Ranch", "Fairfield", "Fallbrook", 
    "Farmersville", "Fawnskin", "Feather Falls", "Fiddletown", 
    "Fillmore", "Firebaugh", "Fish Camp", "Flournoy", 
    "Fontana", "Forbestown", "Foreign Country", "Forest Falls", 
    "Forest Ranch", "Fort Bragg", "Fort Jones", "Fountain Valley", 
    "Frazier Park", "Fremont", "Fresno", "Friant", 
    "Fruto", "Fullerton", "Galt", "Garberville", 
    "Garden Grove", "Gardena", "Gaviota", "Gazelle", 
    "Gerber", "Gilroy", "Glassell Park", "Glencoe", 
    "Glendale", "Glendora", "Glenhaven", "Glenn", 
    "Golden", "Goleta", "Gorman", "Graeagle", 
    "Granada Hills", "Grand Terrace", "Grass Valley", "Green Valley", 
    "Green Valley Lake", "Greenview", "Greenville", "Grenada", 
    "Gridley", "Groveland", "Gustine", "Hacienda Heights", 
    "Hailey", "Hamilton City", "Hanford", "Harbor City", 
    "Hawaiian Gardens", "Hawthorne", "Hayward", "Heber", 
    "Helendale", "Hemet", "Hermosa Beach", "Hesperia", 
    "Hidden Hills", "Hidden Valley Lake", "Highland", "Highland Park", 
    "Hilmar", "Hinkley", "Hollister", "Hollywood", 
    "Hollywood Hills", "Hollywood Hills East", "Homeland", "Hornbrook", 
    "Horse Creek", "Huntington Beach", "Huntington Park", "Idyllwild", 
    "Igo", "Imperial", "Imperial Beach", "Incline Village", 
    "Indian Wells", "Indianapolis", "Indio", "Inglewood", 
    "Ione", "Irvine", "Irwindale", "Jackson", 
    "Jamul", "Johnson Valley", "Johnsville", "Joshua Tree", 
    "Julian", "Juniper Hills", "Kelseyville", "Kerman", 
    "King & Queen", "Kingsburg", "Kirkwood", "La Canada", 
    "La Canada Flintridge", "La Crescenta", "La Grange", "La Habra", 
    "La Habra Heights", "La Jolla", "La Mesa", "La Mirada", 
    "La Palma", "La Puente", "La Quinta", "La Verne", 
    "Ladera Ranch", "Lafayette", "Laguna Beach", "Laguna Hills", 
    "Laguna Niguel", "Laguna Woods", "Lahaina", "Lake Almanor", 
    "Lake Arrowhead", "Lake Balboa", "Lake Elizabeth", "Lake Elsinore", 
    "Lake Forest", "Lake Havasu City", "Lake Hughes", "Lake Isabella", 
    "Lake Los Angeles", "Lake Sherwood", "Lakehead", "Lakeport", 
    "Lakeside", "Lakeview", "Lakeview Terrace", "Lakewood", 
    "Lamont", "Lancaster", "Landers", "Langley", 
    "Las Vegas", "Lathrop", "Laton", "Laughlin", 
    "Lawndale", "Le Grand", "Lebec", "Leimert Park", 
    "Lemon Grove", "Lemoore", "Lennox", "Leona Valley", 
    "Lincoln Heights", "Lindsay", "Lisbon", "Little River", 
    "Little Rock", "Live Oak", "Livermore", "Livingston", 
    "Llano", "Loch Lomond", "Lodi", "Loma Linda", 
    "Loma Rica", "Lomita", "Lompoc", "Long Beach", 
    "Longmont", "Los Alamitos", "Los Altos", "Los Angeles", 
    "Los Banos", "Los Molinos", "Los Olivos", "Los Osos", 
    "Louisville", "Lower Lake", "Lucerne", "Lucerne Valley", 
    "Lynwood", "Lytle Creek", "Madera", "Magalia", 
    "Malibu", "Mammoth Lakes", "Manhattan Beach", "Manteca", 
    "Manton", "Mar Vista", "Maricopa", "Marina", 
    "Marina del Rey", "Mariposa", "Marysville", "Maywood", 
    "Mc Farland", "Mead Valley", "Mecca", "Mendota", 
    "Menifee", "Menlo Park", "Mentone", "Merced", 
    "Miami", "Middletown", "Midpines", "Midway City", 
    "Mill Creek", "Mineral", "Mira Loma", "Mira Mesa", 
    "Mission Hills San Fernando", "Mission Viejo", "Mobile", "Modesto", 
    "Modjeska Canyon", "Mojave", "Mokelumne Hill", "Monrovia", 
    "Montague", "Montclair", "Montebello", "Montecito", 
    "Montecito Heights", "Monterey Park", "Montrose", "Moorpark", 
    "Moreno Valley", "Morgan Hill", "Morongo Valley", "Morro Bay", 
    "Moselle", "Mount Baldy", "Mount Washington", "Mountain Center", 
    "Mountain Home Village", "Mountain Ranch", "Murphys", "Murrieta", 
    "Napa", "National City", "Needles", "Nelson", 
    "Newark", "Newark City", "Newberry Springs", "Newbury Park", 
    "Newhall", "Newman", "Newport Beach", "Newport Coast", 
    "Newville", "Nice", "Nipomo", "Norco", 
    "North Edwards", "North Fork", "North Hills", "North Hollywood", 
    "North Las Vegas", "North Shore", "North Tustin", "Northridge", 
    "Norwalk", "Novato", "Nuevo", "O Neals", 
    "Oak Glen", "Oak Hills", "Oak Park", "Oak View", 
    "Oakdale", "Oakhurst", "Oakland", "Oakley", 
    "Ocean Beach", "Oceano", "Oceanside", "Ojai", 
    "Olivehurst", "Omo Ranch", "Ontario", "Orange", 
    "Orange Park Acres", "Orcutt", "Orland", "Oroville", 
    "Other", "Other Out of Area", "Out of Area", "Out of State", 
    "Oxnard", "Pacific Beach", "Pacific Grove", "Pacific Palisades", 
    "Pacoima", "Pala", "Palermo", "Palm Desert", 
    "Palm Springs", "Palmdale", "Palms", "Palo Verde", 
    "Palomar Mountain", "Palos Verdes Estates", "Palos Verdes Peninsula", "Panorama City", 
    "Paradise", "Paramount", "Pasadena", "Paskenta", 
    "Paso Robles", "Patterson", "Pauma Valley", "Paynes Creek", 
    "Pearblossom", "Perris", "Petaluma", "Phelan", 
    "Phillips Ranch", "Pico Rivera", "Pine Cove", "Pine Grove", 
    "Pine Mountain Club", "Pine Valley", "Pinon Hills", "Pioneer", 
    "Pioneertown", "Piru", "Pismo Beach", "Placentia", 
    "Placerville", "Planada", "Platina", "Playa del Rey", 
    "Playa Vista", "Pleasanton", "Plymouth", "Pomona", 
    "Pope Valley", "Port Hueneme", "Porterville", "Portland", 
    "Portola", "Potter Valley", "Poway", "Prattville", 
    "Prescott", "Princeton", "Proberta", "Quail Valley", 
    "Quartz Hill", "Quenemo", "Quincy", "Rackerby", 
    "Rail Road Flat", "Rainbow", "Ramona", "Rancho Bernardo", 
    "Rancho California", "Rancho Cordova", "Rancho Cucamonga", "Rancho Dominguez", 
    "Rancho Mirage", "Rancho Palos Verdes", "Rancho Santa Fe", "Rancho Santa Margarita", 
    "Raymond", "Red Bluff", "Redding", "Redlands", 
    "Redondo Beach", "Redwood City", "Reedley", "Reseda", 
    "Rialto", "Richmond", "Richvale", "Ridgecrest", 
    "Rimforest", "River Pines", "Riverside", "Rodeo", 
    "Rolling Hills", "Rolling Hills Estates", "Romoland", "Rosamond", 
    "Rosemead", "Roseville", "Rosewood", "Rossmoor", 
    "Rowland Heights", "Rubidoux", "Running Springs Area", "Sacramento", 
    "Salinas", "Salton City", "Salton Sea Beach", "San Andreas", 
    "San Antonio", "San Bernardino", "San Bruno", "San Buenaventura", 
    "San Clemente", "San Diego", "San Dimas", "San Fernando", 
    "San Francisco", "San Gabriel", "San Jacinto", "San Jose", 
    "San Juan Capistrano", "San Leandro", "San Luis Obispo", "San Marcos", 
    "San Marino", "San Mateo", "San Miguel", "San Pedro", 
    "San Ramon", "Sand City", "Sanger", "Santa Ana", 
    "Santa Barbara", "Santa Clara", "Santa Clarita", "Santa Cruz", 
    "Santa Fe Springs", "Santa Margarita", "Santa Maria", "Santa Monica", 
    "Santa Paula", "Santa Rosa", "Santa Ynez", "Santee", 
    "Sarasota", "Saticoy", "Saugus", "Seal Beach", 
    "Seeley", "Selma", "Shadow Hills", "Shafter", 
    "Shasta Lake", "Shaver Lake", "Sherman Oaks", "Shingletown", 
    "Sierra City", "Sierra Madre", "Signal Hill", "Silverado Canyon", 
    "Simi Valley", "Sky Valley", "Snelling", "Solana Beach", 
    "Solvang", "Somerset", "Somis", "Sonoma", 
    "Sonora", "South Bend", "South Dos Palos", "South El Monte", 
    "South Gate", "South Lake Tahoe", "South Pasadena", "South San Francisco", 
    "Spring Valley", "Springville", "Squaw Valley", "Stanton", 
    "Stevenson Ranch", "Stirling City", "Stockton", "Stonyford", 
    "Studio City", "Sugarloaf", "Summerland", "Sun City", 
    "Sun Valley", "Sun Village", "Sunland", "Sunset Beach", 
    "Surfside", "Susanville", "Sutter Creek", "Sylmar", 
    "Taft", "Tahoe City", "Tarzana", "Taylorsville", 
    "Tehachapi", "Tehama", "Temecula", "Temple City", 
    "Thermal", "Thermalito", "Thousand Oaks", "Thousand Palms", 
    "Tipton", "Toluca Lake", "Topanga", "Torrance", 
    "Trabuco Canyon", "Tracy", "Truckee", "Tucson", 
    "Tujunga", "Tulare", "Turlock", "Tustin", 
    "Twain Harte", "Twin Peaks", "Ukiah", "Union City", 
    "Upland", "Upper Lake", "Vacaville", "Val Verde Park", 
    "Valencia", "Valinda", "Vallejo", "Valley Center", 
    "Valley Glen", "Valley Springs", "Valley Village", "Van Nuys", 
    "Venice", "Ventura", "Vernon", "Victor Valley", 
    "Victorville", "Villa Park", "Vina", "Visalia", 
    "Vista", "Volcano", "Wallace", "Walnut", 
    "Walnut Park", "Warner Springs", "Wasco", "Watsonville", 
    "Wawona", "Weed", "Weldon", "West Covina", 
    "West Hills", "West Hollywood", "West Los Angeles", "West Point", 
    "West Sacramento", "Westchester", "Westlake Village", "Westminster", 
    "Westwood", "Wheatland", "Whitefish", "Whitewater", 
    "Whittier", "Wildomar", "Willows", "Wilmington", 
    "Wilseyville", "Winchester", "Winnetka", "Winton", 
    "Wishon", "Wofford Heights", "Woodcrest", "Woodland", 
    "Woodland Hills", "Wrightwood", "Yankee Hill", "Yorba Linda", 
    "Yosemite", "Yreka", "Yuba City", "Yucaipa", 
    "Yucca Valley"]
end
